module.exports = {
  'array-bracket-spacing': ['error', 'never'],
  'block-spacing': 'error',
  'brace-style': ['error', '1tbs'],
  'comma-dangle': ['error', 'always-multiline'],
  'comma-spacing': 'error',
  'comma-style': 'error',
  'eol-last': 'error',
  'func-style': ['error', 'expression', { allowArrowFunctions: true }],
  'key-spacing': 'error',
  'keyword-spacing': 'error',
  'lines-between-class-members': ['error', 'always'],
  'max-len': ['warn', { code: 100, ignoreUrls: true }],
  'new-cap': 'error',
  'new-parens': 'error',
  'no-array-constructor': 'error',
  'no-lonely-if': 'error',
  'no-mixed-spaces-and-tabs': 'error',
  'no-multiple-empty-lines': ['error', { max: 1 }],
  'no-nested-ternary': 'error',
  'no-trailing-spaces': 'error',
  'quotes': ['error', 'single'],
  'semi': ['error', 'always'],
  'space-before-blocks': 'error',
  'space-before-function-paren': ['error', {
    anonymous: 'always',
    named: 'never',
    asyncArrow: 'always',
  }],
};
