module.exports = {
  env: {
    commonjs: true,
    es6: true,
    node: true,
  },
  extends: ['standard'],
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    camelcase: 'error',
    'no-return-await': 'error',
    'no-use-before-define': 'error',
    'no-var': 'error',
    'no-console': 'error',
    'no-undef': 'error',
    'no-unused-vars': 'error',
    'no-useless-return': 'error',
    'no-useless-concat': 'error',
    'no-useless-catch': 'error',
    'no-useless-constructor': 'error',
    'prefer-template': 'error',
    'prefer-object-spread': 'error',
    'no-unneeded-ternary': ['error', { defaultAssignment: false }],
    'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 1, maxBOF: 1 }],
    'func-style': ['error', 'expression', { allowArrowFunctions: true }],
    'import/no-extraneous-dependencies': ['warn', { devDependencies: ['*.test.js'] }],
    semi: ['error', 'always'],
    'space-before-function-paren': ['error', {
      anonymous: 'always',
      named: 'never',
      asyncArrow: 'always',
    }],
    'comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'never',
      exports: 'never',
      functions: 'never',
    }],
    'consistent-return': ['error', { treatUndefinedAsUnspecified: true }],
    'no-underscore-dangle': ['error', { allow: ['_id'], enforceInMethodNames: true }],
    'newline-per-chained-call': ['error', { ignoreChainWithDepth: 2 }],
    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'no-empty': ['error', { allowEmptyCatch: true }],
    'prefer-destructuring': ['error',
      { array: true, object: true },
      { enforceForRenamedProperties: false },
    ],
    'operator-linebreak': ['error', 'before'],
    'multiline-ternary': ['error', 'always-multiline'],
    quotes: ['error', 'single', { allowTemplateLiterals: false }],
    'object-shorthand': ['error', 'always'],
    'object-curly-spacing': ['error', 'always'],
    'array-bracket-spacing': ['error', 'never'],
    'space-before-blocks': 'error',
    'template-curly-spacing': ['error', 'never'],
    'max-len': ['error', { code: 100, comments: 92, ignoreUrls: true, ignoreRegExpLiterals: true }],
    'max-lines': ['error', { max: 260, skipBlankLines: true }],
    'max-lines-per-function': ['error', { max: 60, skipBlankLines: true, IIFEs: true }],
    'max-classes-per-file': ['error', 1],
    'max-statements-per-line': ['error', { max: 1 }],
    'max-depth': ['error', 4],
    'max-nested-callbacks': ['error', 3],
    'max-params': ['error', 4],
    'max-statements': ['error', 18],
    'arrow-parens': ['error', 'always', { requireForBlockBody: true }],
  },
};
